languageCode = "fr"
languageName = "French"
displayName = ":fr:"
isoCode = "fr"
weight = 3
rtl = false

title = "Sofiene Khiari"

[author]
name = "Sofiene Khiari"
image = "profile_picture.jpg"
headline = "Pharmacien & Développeur de Logiciels"
links = [
    { github = "https://github.com/sofienekhiari"},
    { linkedin = "https://www.linkedin.com/in/khiarisofiene"},
    { medium = "https://medium.com/@sofienekhiari" },
    { email = "mailto:sofiene.khiari@stud.unibas.ch" },
]
