[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 15

[[main]]
  name = "Uses"
  pageRef = "uses"
  weight = 20

[[main]]
  name = "GitHub"
  url = "https://github.com/sofienekhiari"
  weight = 30
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"
