colorScheme = "slate"
enableSearch = true
enableCodeCopy = true

[author]
name = "Sofiene Khiari"
image = "profile_picture.jpg"
headline = "Pharmacist & Software Developer"
links = [
    { github = "https://github.com/sofienekhiari"},
    { linkedin = "https://www.linkedin.com/in/khiarisofiene"},
    { medium = "https://medium.com/@sofienekhiari" },
    { email = "mailto:sofiene.khiari@stud.unibas.ch" },
]

[header]
layout = "hybrid"

[footer]
showThemeAttribution = false
showAppearanceSwitcher = true

[homepage]
layout = "profile"
showRecent = false

[article]
showDate = false
showAuthor = false
showBreadcrumbs = false
showDraftLabel = false
showEdit = false
editAppendPath = true
showHeadingAnchors = false
showPagination = false
showReadingTime = false

[list]
showBreadcrumbs = false
showSummary = false
groupByYear = false

[taxonomy]
showTermCount = true

[sitemap]
excludedKinds = ["taxonomy", "term"]